couponswaphub/conversation/urls.py
from django.urls  import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/<int:coupon_pk>/',views.new_conversation,name='new'),
]

couponswaphub/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .import views
from .forms import LoginForm

app_name= 'core'

urlpatterns= [
    path('',views.index,name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),name='login'),
]

couponswaphub/coupon/urls.py
from django.urls import path

from .import views

app_name='coupon'

urlpatterns=[
    path('',views.coupons, name='coupons'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
]

couponswaphub/couponswaphub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('core.urls')),
    path('coupons/',include('coupon.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

couponswaphub/coupon/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
   name= models.CharField(max_length=255)

   class Meta:
      ordering=('name',)
      verbose_name_plural='Categories'

   def __str__(self):
      return self.name

class Coupon(models.Model):
   category=models.ForeignKey(Category,related_name='coupons',on_delete=models.CASCADE)
   name=models.CharField(max_length=255)
   description=models.TextField(blank=True,null=True)
   image=models.ImageField(upload_to='coupon_images',blank=True,null=True)
   is_booked=models.BooleanField(default=False)
   published_by=models.ForeignKey(User,related_name='coupon',on_delete=models.CASCADE)
   published_at=models.DateTimeField(auto_now_add=True)

   def __str__(self):
      return self.name

couponswaphub/coupon/forms.py
from django import forms

from .models import Coupon

INPUT_CLASSES='w-full py-4 px-6 rounded-xl border'
class NewCouponForm(forms.ModelForm):
    class Meta:
        model=Coupon
        fields=('category','name','description','image',)
        widgets= {
            'category':forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                 'class':INPUT_CLASSES
             }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class':INPUT_CLASSES
            })
        }

class EditCouponForm(forms.ModelForm):
    class Meta:
       model = Coupon
       fields = ('name', 'description', 'image','is_booked')
       widgets = {
        'name': forms.TextInput(attrs={
         'class': INPUT_CLASSES
         }),
        'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
         }),
        'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES
        })
        }

couponswaphub/coupon/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from.forms import NewCouponForm,EditCouponForm
from .models import Category,Coupon
# Create your views here.


def coupons(request):
    query=request.GET.get('query','')
    category_id=request.GET.get('category',0)
    categories=Category.objects.all()
    coupons=Coupon.objects.filter(is_booked=False)

    if category_id:
        coupons=coupons.filter(category_id=category_id)

    if query:
        coupons=coupons.filter(Q(name__icontains=query) |Q(description__icontains=query) )
    return render(request,'coupon/coupons.html',{
        'coupons':coupons,
        'query':query,
        'categories':categories,
        'category_id':int(category_id)
    })
def detail(request,pk):
    coupon =get_object_or_404(Coupon,pk=pk)
    related_coupons=Coupon.objects.filter(category=coupon.category,is_booked=False).exclude(pk=pk)[0:3]

    return render(request,'coupon/detail.html',{
        'coupon':coupon,
        'related_coupons':related_coupons
    })

@login_required()
def new(request):
    if request.method=='POST':
        form=NewCouponForm(request.POST,request.FILES)

        if form.is_valid():
            coupon=form.save(commit=False)
            coupon.published_by=request.user
            coupon.save()

            return redirect('coupon:detail',pk=coupon.id)

    else:
       form=NewCouponForm()

    return render(request,'coupon/form.html',{
        'form':form,
        'title':'New coupon'
    })

@login_required()
def edit(request,pk):
    coupon=get_object_or_404(Coupon,pk=pk ,published_by=request.user)

    if request.method=='POST':
        form=EditCouponForm(request.POST,request.FILES,instance=coupon)

        if form.is_valid():
           form.save()

           return redirect('coupon:detail',pk=coupon.id)

    else:
       form=EditCouponForm(instance=coupon)

    return render(request,'coupon/form.html',{
        'form':form,
        'title':'Edit coupon'
    })


@login_required
def delete(request,pk):
    coupon=get_object_or_404(Coupon,pk=pk,published_by=request.user)
    coupon.delete()

    return redirect('dashboard:index')

couponswaphub/coupon/templates/coupon/coupons.html
{% extends 'core/base.html' %}

{% block title %}Coupons{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'coupon:coupons' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a different category coupons">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">
            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                <li class="py-2 px-2 rounded-xl{% if category.id == category_id %}  bg-gray-200{% endif %}">
                    <a href ="{% url 'coupon:coupons' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>

            <hr class="my-6">
            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'coupon:coupons' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
            {% for coupon in coupons %}
              <div>
                  <a href="{% url 'coupon:detail' coupon.id %}">
                      <div>
                          <img src="{{coupon.image.url}}" class="rounded-t-xl">
                      </div>

                      <div class="p-6 bg-white rounded-b-xl">
                          <h2 class="text-2xl">{{ coupon.name }} </h2>
                      </div>
                  </a>
              </div>
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

couponswaphub/coupon/templates/coupon/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ coupon.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ coupon.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ coupon.name }} </h1>
        <p class="text-gray-500"><strong>Owner</strong>{{ coupon.published_by.username }}</p>

        {% if coupon.description %}
          <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong><br>
            {{ coupon.description }}
          </p>
        {% endif %}

        {% if request.user == coupon.published_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your coupon!</p>
                <a href="{% url 'coupon:edit' coupon.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'coupon:delete' coupon.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}
             <a href="{% url 'conversation:new' coupon.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact owner</a>
        {% endif %}
    </div>
</div>
 <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center ">Related coupons</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for coupon in related_coupons %}
              <div>
                  <a href="{% url 'coupon:detail' coupon.id %}">
                      <div>
                          <img src="{{coupon.image.url}}" class="rounded-t-xl">
                      </div>

                      <div class="p-6 bg-white rounded-b-xl">
                          <h2 class="text-2xl">{{ coupon.name }} </h2>
                      </div>
                  </a>
              </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

couponswaphub/coupon/templates/coupon/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
             <div class="mb-3 p-6 bg-red-100 rounded-xl">
                 {% for field in form %}
                    {{ field.errors }}
                 {% endfor %}

                 {{ form.non_field_errors }}
             </div>
    {% endif %}

     <button class=" mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}